export const ROUTE_TYPE_LABELS: Record<string, string> = {
  utama: 'Rapid Bus (Trunk)',
  tempatan: 'Rapid Bus (Local)',
  bet: 'Bus Expressway Transit (BET)',
  drt: 'Demand Responsive Transit (DRT)',
  mbpj: 'PJ City Bus',
  mbsa: 'Smart Selangor Bus (Shah Alam)',
  mbsj: 'Smart Selangor Bus (Subang Jaya)',
  mbdk: 'Smart Selangor Bus (Klang)',
  mpaj: 'Smart Selangor Bus (Ampang Jaya)',
  mpkj: 'Smart Selangor Bus (Kajang)',
  mps: 'Smart Selangor Bus (Selayang)',
  nadiputra: 'Nadi Putra Bus',
  mpkl: 'Smart Selangor Bus (Kuala Langat)',
  lrt_feeder: 'LRT Feeder Bus',
  mrt_feeder: 'MRT Feeder Bus',
}
